version: "3.6"
x-mongomain: &mongo
  image: mongo:latest
  volumes:
    - /home/mongo:/data/db
  networks:
    - "mongo"
 
services:

  mongo-0:
       <<: *mongo
       deploy:
         placement:
           constraints:
             - node.hostname == hostname1
       entrypoint: [ "/usr/bin/mongod", "--replSet", "rs6", "--bind_ip", "0.0.0.0", "--wiredTigerCacheSizeGB", "3"]
  mongo-1:
       <<: *mongo
       deploy:
         placement:
           constraints:
             - node.hostname == hostname2
       entrypoint: [ "/usr/bin/mongod", "--replSet", "rs6", "--bind_ip", "0.0.0.0", "--wiredTigerCacheSizeGB", "3"]       
  mongo-2:
       <<: *mongo
       deploy:
         placement:
           constraints:
             - node.hostname == hostname3
       entrypoint: [ "/usr/bin/mongod", "--replSet", "rs6", "--bind_ip", "0.0.0.0", "--wiredTigerCacheSizeGB", "3"]
networks:
    mongo:
      driver:  overlay 
